### ISSUE TITLE
【问题】这个的停靠系统有demo吗？

### ISSUE THREAD

**Issue by KnIfER** [xfcanyue/DuiLib_DuiEditor#1]
编译要MFC，好复杂，有没有简单一点的demo好上手？

**Comment by xfcanyue** [comment]
编译需要MFC一点都不复杂啊，MFC向导建立的程序就有停靠各种停靠窗口。

**Comment by KnIfER** [comment]
哦。还想问这种程序（duilib或者duilib+mfc）能用wine在linux上面运行吗？(C盘就一两个G，试不了)

**Comment by xfcanyue** [comment]
支持svg

**Comment by KnIfER** [comment]
是您为DuiLib扩展的功能吗？

**Comment by xfcanyue** [comment]
是的呀。
