### ISSUE TITLE
缺少DuiEditor.xml文件

### ISSUE THREAD

**Issue by ecrasy** [xfcanyue/DuiLib_DuiEditor#3]
bin目录缺少DuiEditor.xml
使用vs2017编译，debug版本
运行程序异常中断于 DuiEditor\MySplitterWnd.cpp +157行
![DuiEditor](https://user-images.githubusercontent.com/10347096/152685710-ba0304f1-a121-4d11-a387-438d4e80564c.jpg)

**Comment by xfcanyue** [comment]
设计器只支持unicode版本

**Comment by ecrasy** [comment]
xsUnicode和Unicode的Debug和Release版本，编译测试都会出现同样的错误提示
