### ISSUE TITLE
修复：修改颜色值 时，保留 xml 里的颜色透明度

### ISSUE THREAD

**Issue by HackerJLY** [xfcanyue/DuiLib_DuiEditor#8]
修复：修改颜色值 时，保留 xml 里的颜色透明度

![image](https://github.com/user-attachments/assets/044cb356-3166-4b0d-8cde-d95b2ebaf8b5)
![image](https://github.com/user-attachments/assets/f7ee6c3d-8619-4002-b908-f77bb63a8c62)

**Comment by xfcanyue** [comment]
已提交。
